[package]
name = "ai_wargame"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
derive_more = "0.99.17"
ndarray = { version = "0.15.6", features = ["serde"] }
#duplicate = "1.0.0"
anyhow = "1.0.70"
#htmltree = { rev = "0.4.0", git = "https://github.com/massimofasciano/htmltree" }
#htmltree = { path = "../htmltree" }
